sudo: required
services:
  - docker

before_install:
  - docker build -t aviboinidocker/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aviboinidocker/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dockerReact"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-206018806401"
  bucket_path: "dockerReact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
